### ISSUE TITLE
cheapest?

### ISSUE THREAD

**Issue by qyloxe** [sibblegp/b2blaze#3]
well, obviously you write about "object storage" which you assume is cheapest in B2, but if you consider cloud storage, than B2 is VERY costly. 

According to B2 pricing:
https://www.backblaze.com/b2/cloud-storage-pricing.html#
The cost of just storing 10TB would be more about $700 per year.

In OVH with their solution "hubic", the cost of operations at 10TB scale, per year is only Eur 50. 
https://hubic.com/en/offers/

Besides of that, your library is excellent on its own, so if you would consider in the future adding another cloud providers (i.e. hubic) it would be more than superb.

**Comment by tghw** [comment]
This is a B2 library, not a general storage library, not an S3 library, not a hubic library.

**Comment by sibblegp** [comment]
Considering that hubic's website is completely broken so I can't even tell if they are cloud storage or not (they appear to be P2P) and I am basing my claim of cheapest off of Backblaze's claim, I am giing to close this.  As also said, this is a backblaze only library, not a general storage library. Take care!
