### ISSUE TITLE
Upload files without opening them

### ISSUE THREAD

**Issue by tghw** [sibblegp/b2blaze#4]
In its current implementation, it looks like you have to read in the entire file before uploading, which is memory intensive/prohibitive when working with large files. It would be nice to be able to pass an open file object that is streamed to the server.

Requests already supports file objects, the big change will be calculating the sha1 hash.

**Comment by sibblegp** [comment]
Requests file's feature is to send in files in a dict for named fields, usually on a web form. To send in files to b2, you must use the data property. And as you said, I'm not sure how to calculate a sha1 with an unopened file.

This is an interesting idea though so I'm going to leave it open. If anyone has any implementation thoughts, please let me know.

**Comment by tghw** [comment]
`requests` can also take the file as the `data` field. See http://docs.python-requests.org/en/master/user/advanced/#streaming-uploads

**Comment by sibblegp** [comment]
Ah, very good call. Such a complex library. Now we just need to figure out how to calculate a standing sha1.

**Comment by sibblegp** [comment]
Here we can use buffers: https://stackoverflow.com/questions/22058048/hashing-a-file-in-python

**Comment by ptrks** [comment]
Checkout the references to `hex_digits_at_end ` [here](https://www.backblaze.com/b2/docs/uploading.html).

**Comment by sibblegp** [comment]
> Checkout the references to hex_digits_at_end here.

We still need to calculate the sha1 though. I don't think this takes away the calculation requirement.

**Comment by tghw** [comment]
I would need to sit down and do some testing, but I believe it would look something like this in `connector.py`:

```
BUF_SIZE = 1024 # 1k at a time? Not sure that's the best choice, but should be fine

....

if hasattr(file_contents, 'read'): # If it has `read`, then it's a file-like object that we can stream
  sha = sha1()
  buf = file_contents.read(BUF_SIZE)
  file_size = len(buf)
  while len(buf) > 0:
    sha.update(buf)
    buf = file_contents.read(BUF_SIZE)
  file_sha = sha.hexdigest()
  file_contents.seek(0) # Reset to beginning
# Otherwise, continue as usual
 ```

The only catch I can think of is file size, though the `requests` docs say that the `Content-Length` header is automatically added, so maybe just some logic not to manually add the header if it's a file object.

On a related note, I'm not sure that `sys.getsizeof()` is the right way to get the length of the content. It seems to get the size of the object in memory, but that includes some memory overhead. That said, it seems that `Content-Length` is [overwritten anyway](https://stackoverflow.com/questions/43458712/python-requests-form-data-adding-content-length-to-each-request/43458846), so I think it could be removed in both cases and still work.

**Comment by tghw** [comment]
Yeah, `Content-Length` is overridden: http://docs.python-requests.org/en/master/user/quickstart/?highlight=content-length#custom-headers

**Comment by sibblegp** [comment]
You're right about content-length.  I'll fix it.

**Comment by sibblegp** [comment]
Pushed!  Enjoy!

**Comment by ptrks** [comment]
@sibblegp Oh yea I wasn't saying calculation isn't required. Looking at the links you posted you could start the streaming request with the `hex_digits_at_end` header value and update the hash as the chunks are processed and write the final hash value at the end.

**Comment by sibblegp** [comment]
@patrick--  Ah, very interesting.  I'll consider that.
