### ISSUE TITLE
Add Multithreaded Large File Upload

### ISSUE THREAD

**Issue by sibblegp** [sibblegp/b2blaze#7]
Add multithreading to file uploads. Check file size before uploading to prevent error.

**Comment by mitchellhuang** [comment]
I might take a stab at writing a PR for this. Which library should be used: multithreading, multiprocessing, or asyncio? My understanding of Python's GIL is that for socket IO operations like a download/upload we should be fine with threads.

Edit - Started working on it here: https://github.com/mitchellhuang/b2blaze/tree/upload-large-file
